"""Reusable hosting for Tesserix MCP servers."""

from importlib.metadata import version as _distribution_version

from tesserix_mcp_runtime.application import (
    Application,
    ApplicationConfigurationError,
    ApplicationDeadlineExceeded,
    ApplicationDiagnostic,
    ApplicationDiagnosticCode,
    ApplicationEndpoint,
    ApplicationLimits,
    ApplicationRunResult,
    ApplicationTransport,
    ShutdownSignal,
    ShutdownSignalSource,
)
from tesserix_mcp_runtime.clock import SystemClock
from tesserix_mcp_runtime.contracts import (
    ApprovalRequirement,
    AuthenticatedIdentity,
    Authorizer,
    CallContext,
    Cancellation,
    Clock,
    CredentialProvider,
    ErrorCode,
    ErrorResponse,
    IdempotencyRequirement,
    InvocationResult,
    InvocationStatus,
    JsonValue,
    Lifecycle,
    LifecycleState,
    Retryability,
    Telemetry,
    ToolDefinition,
    ToolDiscoveryMetadata,
    ToolEffect,
    ToolHandler,
    ToolMetadata,
    TraceContext,
)
from tesserix_mcp_runtime.errors import (
    MappedError,
    RuntimeFailure,
    ScrubbedError,
    TerminalEmitter,
    map_exception,
)
from tesserix_mcp_runtime.lifecycle import (
    LifecycleController,
    LifecycleFailure,
    LifecycleTransitionError,
)
from tesserix_mcp_runtime.policy import (
    ApprovalRecord,
    ApprovalStore,
    ApprovalUse,
    ToolPolicy,
    ToolPolicyAuditEvent,
    ToolPolicyAuditSink,
    ToolPolicyConfigurationError,
    ToolPolicyDecision,
    ToolPolicyRule,
    ToolPolicyState,
    ToolReview,
    tool_policy_fingerprint,
)
from tesserix_mcp_runtime.schema_compatibility import (
    SchemaChange,
    SchemaDirection,
    classify_schema_change,
)
from tesserix_mcp_runtime.tool import (
    ContractViolation,
    DuplicateToolName,
    MetadataPolicy,
    SchemaPolicy,
    ToolCatalog,
    normalize_tool_name,
)
from tesserix_mcp_runtime.tool_manifest import ToolManifest, schema_fingerprint

__version__ = _distribution_version("tesserix-mcp-runtime")

__all__ = [
    "Application",
    "ApplicationConfigurationError",
    "ApplicationDeadlineExceeded",
    "ApplicationDiagnostic",
    "ApplicationDiagnosticCode",
    "ApplicationEndpoint",
    "ApplicationLimits",
    "ApplicationRunResult",
    "ApplicationTransport",
    "ApprovalRecord",
    "ApprovalRequirement",
    "ApprovalStore",
    "ApprovalUse",
    "AuthenticatedIdentity",
    "Authorizer",
    "CallContext",
    "Cancellation",
    "Clock",
    "ContractViolation",
    "CredentialProvider",
    "DuplicateToolName",
    "ErrorCode",
    "ErrorResponse",
    "IdempotencyRequirement",
    "InvocationResult",
    "InvocationStatus",
    "JsonValue",
    "Lifecycle",
    "LifecycleController",
    "LifecycleFailure",
    "LifecycleState",
    "LifecycleTransitionError",
    "MappedError",
    "MetadataPolicy",
    "Retryability",
    "RuntimeFailure",
    "SchemaChange",
    "SchemaDirection",
    "SchemaPolicy",
    "ScrubbedError",
    "ShutdownSignal",
    "ShutdownSignalSource",
    "SystemClock",
    "Telemetry",
    "TerminalEmitter",
    "ToolCatalog",
    "ToolDefinition",
    "ToolDiscoveryMetadata",
    "ToolEffect",
    "ToolHandler",
    "ToolManifest",
    "ToolMetadata",
    "ToolPolicy",
    "ToolPolicyAuditEvent",
    "ToolPolicyAuditSink",
    "ToolPolicyConfigurationError",
    "ToolPolicyDecision",
    "ToolPolicyRule",
    "ToolPolicyState",
    "ToolReview",
    "TraceContext",
    "__version__",
    "classify_schema_change",
    "map_exception",
    "normalize_tool_name",
    "schema_fingerprint",
    "tool_policy_fingerprint",
]
