"""Reusable hosting for Tesserix MCP servers."""

from importlib.metadata import version as _distribution_version

from tesserix_mcp_runtime.application import (
    Application,
    ApplicationConfigurationError,
    ApplicationDeadlineExceeded,
    ApplicationDiagnostic,
    ApplicationDiagnosticCode,
    ApplicationEndpoint,
    ApplicationLimits,
    ApplicationRunResult,
    ApplicationTransport,
    ShutdownSignal,
    ShutdownSignalSource,
)
from tesserix_mcp_runtime.clock import SystemClock
from tesserix_mcp_runtime.contracts import (
    ApprovalRequirement,
    AuthenticatedIdentity,
    Authorizer,
    CallContext,
    Cancellation,
    Clock,
    CredentialProvider,
    ErrorCode,
    ErrorResponse,
    IdempotencyRequirement,
    InvocationResult,
    InvocationStatus,
    JsonValue,
    Lifecycle,
    LifecycleState,
    Retryability,
    Telemetry,
    ToolDefinition,
    ToolEffect,
    ToolHandler,
    ToolMetadata,
    TraceContext,
)
from tesserix_mcp_runtime.errors import (
    MappedError,
    RuntimeFailure,
    ScrubbedError,
    TerminalEmitter,
    map_exception,
)
from tesserix_mcp_runtime.lifecycle import (
    LifecycleController,
    LifecycleFailure,
    LifecycleTransitionError,
)
from tesserix_mcp_runtime.tool import ContractViolation, SchemaPolicy, ToolCatalog

__version__ = _distribution_version("tesserix-mcp-runtime")

__all__ = [
    "Application",
    "ApplicationConfigurationError",
    "ApplicationDeadlineExceeded",
    "ApplicationDiagnostic",
    "ApplicationDiagnosticCode",
    "ApplicationEndpoint",
    "ApplicationLimits",
    "ApplicationRunResult",
    "ApplicationTransport",
    "ApprovalRequirement",
    "AuthenticatedIdentity",
    "Authorizer",
    "CallContext",
    "Cancellation",
    "Clock",
    "ContractViolation",
    "CredentialProvider",
    "ErrorCode",
    "ErrorResponse",
    "IdempotencyRequirement",
    "InvocationResult",
    "InvocationStatus",
    "JsonValue",
    "Lifecycle",
    "LifecycleController",
    "LifecycleFailure",
    "LifecycleState",
    "LifecycleTransitionError",
    "MappedError",
    "Retryability",
    "RuntimeFailure",
    "SchemaPolicy",
    "ScrubbedError",
    "ShutdownSignal",
    "ShutdownSignalSource",
    "SystemClock",
    "Telemetry",
    "TerminalEmitter",
    "ToolCatalog",
    "ToolDefinition",
    "ToolEffect",
    "ToolHandler",
    "ToolMetadata",
    "TraceContext",
    "__version__",
    "map_exception",
]
