"""Reusable hosting for Tesserix MCP servers."""

from tesserix_mcp_runtime.contracts import (
    ApprovalRequirement,
    AuthenticatedIdentity,
    Authorizer,
    CallContext,
    Cancellation,
    Clock,
    CredentialProvider,
    ErrorCode,
    ErrorResponse,
    JsonValue,
    IdempotencyRequirement,
    InvocationResult,
    InvocationStatus,
    Lifecycle,
    LifecycleState,
    Retryability,
    Telemetry,
    ToolDefinition,
    ToolEffect,
    ToolHandler,
    ToolMetadata,
    TraceContext,
)
from tesserix_mcp_runtime.errors import (
    MappedError,
    RuntimeFailure,
    ScrubbedError,
    TerminalEmitter,
    map_exception,
)
from tesserix_mcp_runtime.lifecycle import (
    LifecycleController,
    LifecycleFailure,
    LifecycleTransitionError,
)
from tesserix_mcp_runtime.tool import ContractViolation, SchemaPolicy, ToolCatalog

__version__ = "0.1.0.dev0"

__all__ = [
    "ApprovalRequirement",
    "AuthenticatedIdentity",
    "Authorizer",
    "CallContext",
    "Cancellation",
    "Clock",
    "ContractViolation",
    "CredentialProvider",
    "ErrorCode",
    "ErrorResponse",
    "JsonValue",
    "IdempotencyRequirement",
    "InvocationResult",
    "InvocationStatus",
    "Lifecycle",
    "LifecycleController",
    "LifecycleFailure",
    "LifecycleState",
    "LifecycleTransitionError",
    "MappedError",
    "Retryability",
    "RuntimeFailure",
    "ScrubbedError",
    "SchemaPolicy",
    "Telemetry",
    "TerminalEmitter",
    "ToolCatalog",
    "ToolDefinition",
    "ToolEffect",
    "ToolHandler",
    "ToolMetadata",
    "TraceContext",
    "__version__",
    "map_exception",
]
