from __future__ import annotations

from typing import Final, Literal

AUTHORING_MANIFEST_VERSION: Final[Literal["1.0"]] = "1.0"
AUTHORING_MANIFEST_MAX_BYTES: Final = 65_536
AUTHORING_MANIFEST_MAX_DEPTH: Final = 16
AUTHORING_MANIFEST_MAX_NODES: Final = 4_096
OFFICIAL_SCHEMA_VERSION: Final = "2025-12-11"
OFFICIAL_SCHEMA_URL: Final = (
    f"https://static.modelcontextprotocol.io/schemas/{OFFICIAL_SCHEMA_VERSION}/server.schema.json"
)
OFFICIAL_SCHEMA_SHA256: Final = "578b5bb01866d060ff6a67734cf6b2f17a5da283a0877775c7913e4761a626e5"
OFFICIAL_REGISTRY_RELEASE: Final = "v1.8.1"
OFFICIAL_REGISTRY_COMMIT: Final = "f52dc8525a441a3abf5fedc9912152d95af5aab1"
REGISTRY_API_VERSION: Final = "registry.agentic.dev/v1alpha1"
REGISTRY_EXTENSION_KEY: Final = "x-tesserix"

__all__ = [
    "AUTHORING_MANIFEST_MAX_BYTES",
    "AUTHORING_MANIFEST_MAX_DEPTH",
    "AUTHORING_MANIFEST_MAX_NODES",
    "AUTHORING_MANIFEST_VERSION",
    "OFFICIAL_REGISTRY_COMMIT",
    "OFFICIAL_REGISTRY_RELEASE",
    "OFFICIAL_SCHEMA_SHA256",
    "OFFICIAL_SCHEMA_URL",
    "OFFICIAL_SCHEMA_VERSION",
    "REGISTRY_API_VERSION",
    "REGISTRY_EXTENSION_KEY",
]
